site_name: Lanim
site_url: https://decorator-factory.github.io/lanim
edit_uri: https://github.com/decorator-factory/lanim/tree/master/mkdocs/docs
repo_url: https://github.com/decorator-factory/lanim

nav:
  - Home: index.md
  - Tutorial:
    - Installation: tutorial/installation.md
    - Hello, Î»anim!: tutorial/hello.md
    - How does Lanim work?: tutorial/how-does-lanim-work.md
  - How-to guides: howtos.md

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - smarty
  - admonition
  - pymdownx.details
